### ISSUE TITLE
When disabled, parse() drops text after last closing tag.

### ISSUE THREAD

**Issue by markscho** [TrevorBurnham/sty#1]
Examine the following code:
`let x = '<red>Hello</red> World!\r\n';`
`ansi.disable();`
`console.log('[' + ansi.parse(x) + ']');`

What you get is:
[Hello]

Instead, I expected it to be:
[Hello World!
]

**Comment by TrevorBurnham** [comment]
I'm no longer maintaining this project. I'd recommend using one of the more popular ANSI coloring packages, such as [chalk](https://github.com/chalk/chalk).
